---
- name: Example component
  hosts: localhost # On ResearchCloud, the target host is always simply 'localhost'.
  vars:
    alphafold_repo_path: /tmp/alphafold
  gather_facts: true

  roles:
    - role: uusrc.general.fact_regular_users
    - role: uursrc.general.fact_workspace_info

  tasks:
    - name: Update linux
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        name: ca-certificates curl

    - name: Obtain alphafold 3 sourcecode
      ansible.builtin.git:
        repo: https://github.com/google-deepmind/alphafold3.git
        dest: "{{ alphafold_repo_path }}"

    - name: Ensure that permanent storage is available
      when: fact_workspace_storage | length == 0
      ansible.builtin.fail:
        msg: "No permanent storage found on the workspace! Exiting"

    - name: Set path to databases
      ansible.builtin.set_fact:
        db_path: "{{ fact_workspace_storage[0]['mount'] }}"
    
    - name: Create directory on permanent storage
      ansible.builtin.file:
        state: directory
        path: "{{ db_path }}"
        mode: "0750"
        owner: root
        group: docker

    - name: Run fetch_databases
      ansible.builtin.shell: "{{ alphafold_repo_path }}/fetch_databases.sh {{ db_path }}"
      args:
        executable: /bin/bash
